#!/bin/bash

# ============================================================
# Green IT ETL Automation Script
# This script runs a Python ETL job that:
# 1) Extracts data from Oracle
# 2) Exports it to Parquet files
# 3) Syncs the generated files to a GitHub branch
# ============================================================


# ----------------------------
# CONFIGURATION SECTION
# ----------------------------

# Root directory of the Green IT project
PROJECT_DIR="/home/oracle/green_it"

# Absolute path to the Python ETL script responsible for:
# - Connecting to Oracle
# - Running the SQL query
# - Exporting data to Parquet format
PYTHON_SCRIPT="$PROJECT_DIR/X001_Oracle/O_03_LOAD_CSV_DATA/L_02_ETL_Logic/E_02_Export/export_to_parquet.py"

# Directory where Parquet files are generated
# This path is used by Git to stage only exported data files
EXPORT_DIR="$PROJECT_DIR/X001_Oracle/O_03_LOAD_CSV_DATA/L_02_ETL_Logic/E_03_Data_Output"

# Dedicated Git branch used for automated exports
# This branch is typically merged later into main by an admin
BRANCH_NAME="data-pipeline-branch"

# Timestamp used in logs and Git commit message
DATE=$(date +'%Y-%m-%d %H:%M')


# ----------------------------
# PIPELINE START
# ----------------------------

echo "------------------------------------------------"
echo "Starting Green IT ETL Pipeline: $DATE"
echo "------------------------------------------------"


# ----------------------------
# STEP 1: Run Python ETL Script
# ----------------------------

# Execute the Python script using an absolute path to Python
echo "Step 1: Exporting Oracle data to Parquet..."
/usr/bin/python3 $PYTHON_SCRIPT

# Check the exit code of the Python script
if [ $? -ne 0 ]; then
    echo "Error: Step 1 FAILED."
    exit 1
fi


# ----------------------------
# STEP 2: Git Automation
# ----------------------------

# Move to the project root directory
echo "Step 2: Syncing to GitHub..."
cd $PROJECT_DIR || exit 1

# Ensure we are working on the correct export branch
git checkout $BRANCH_NAME

# Stage only Parquet files generated by the ETL process
git add $EXPORT_DIR/*.parquet

# Create a commit with a timestamped, descriptive message
git commit -m "Green IT metrics export - $DATE"

# Push committed files to the remote repository on the same branch
git push origin $BRANCH_NAME
